# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and push kinit-sidecar image to container registry
  inputs:
    command: buildAndPush
    repository: kinit-sidecar
    dockerfile: ./Dockerfile
    containerRegistry: 'cr-connection'
    tags: |      
      latest   
- task: Docker@2
  displayName: Build and push krb5 image to container registry
  inputs:
    command: buildAndPush
    repository: krb5
    dockerfile: ./example-server/Dockerfile
    containerRegistry: 'cr-connection'
    tags: |      
      latest         